export default {
  

   login: "AryamaSinghParihar",
  id: 155705846,
  node_id: "U_kgDOCUfh9g",
  avatar_url: "https://avatars.githubusercontent.com/u/155705846?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/AryamaSinghParihar",
  html_url: "https://github.com/AryamaSinghParihar",
  followers_url: "https://api.github.com/users/AryamaSinghParihar/followers",
  following_url: "https://api.github.com/users/AryamaSinghParihar/following{/other_user}",
  gists_url: "https://api.github.com/users/AryamaSinghParihar/gists{/gist_id}",
  starred_url: "https://api.github.com/users/AryamaSinghParihar/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/AryamaSinghParihar/subscriptions",
  organizations_url: "https://api.github.com/users/AryamaSinghParihar/orgs",
  repos_url: "https://api.github.com/users/AryamaSinghParihar/repos",
  events_url: "https://api.github.com/users/AryamaSinghParihar/events{/privacy}",
  received_events_url: "https://api.github.com/users/AryamaSinghParihar/received_events",
  type: "User",
  site_admin: false,
  name: "Aryama",
  company: "IIT(ISM) Dhanbad",
  blog: "",
  location: "Dhanbad, Jharkhand",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 3,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2024-01-05T04:39:29Z",
   updated_at: "2024-06-21T05:14:03Z"
};
